# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/phy_constr.xdc

# Block Designs: bd/lcd_control/lcd_control.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control || ORIG_REF_NAME==lcd_control} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_processing_system7_0_0/lcd_control_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_processing_system7_0_0 || ORIG_REF_NAME==lcd_control_processing_system7_0_0} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_axi_gpio_0_0/lcd_control_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_axi_gpio_0_0 || ORIG_REF_NAME==lcd_control_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_axi_gpio_0_1/lcd_control_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_axi_gpio_0_1 || ORIG_REF_NAME==lcd_control_axi_gpio_0_1} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_axi_gpio_0_2/lcd_control_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_axi_gpio_0_2 || ORIG_REF_NAME==lcd_control_axi_gpio_0_2} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_axi_gpio_0_3/lcd_control_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_axi_gpio_0_3 || ORIG_REF_NAME==lcd_control_axi_gpio_0_3} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_xbar_0/lcd_control_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_xbar_0 || ORIG_REF_NAME==lcd_control_xbar_0} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_ps7_0_axi_periph_0/lcd_control_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_ps7_0_axi_periph_0 || ORIG_REF_NAME==lcd_control_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_rst_ps7_0_99M_0/lcd_control_rst_ps7_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_rst_ps7_0_99M_0 || ORIG_REF_NAME==lcd_control_rst_ps7_0_99M_0} -quiet] -quiet

# IP: bd/lcd_control/ip/lcd_control_auto_pc_0/lcd_control_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_control_auto_pc_0 || ORIG_REF_NAME==lcd_control_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/prana/Documents/Projects/FPGA-Soc/lcd_control_ps/lcd_control_ps.gen/sources_1/bd/lcd_control/lcd_control_ooc.xdc
