# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/prana/Documents/Projects/FPGA-Soc/lcd_control_ps/lcd_control_ps.srcs/sources_1/bd/lcd_control/ip/lcd_control_auto_pc_0/lcd_control_auto_pc_0.xci
# IP: The module: 'lcd_control_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prana/Documents/Projects/FPGA-Soc/lcd_control_ps/lcd_control_ps.gen/sources_1/bd/lcd_control/ip/lcd_control_auto_pc_0/lcd_control_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_control_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/prana/Documents/Projects/FPGA-Soc/lcd_control_ps/lcd_control_ps.srcs/sources_1/bd/lcd_control/ip/lcd_control_auto_pc_0/lcd_control_auto_pc_0.xci
# IP: The module: 'lcd_control_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prana/Documents/Projects/FPGA-Soc/lcd_control_ps/lcd_control_ps.gen/sources_1/bd/lcd_control/ip/lcd_control_auto_pc_0/lcd_control_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_control_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
