domain_path: C:\Users\prana\Documents\Projects\FPGA-Soc\lcd_control_ps\lcd_control_platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
